### ISSUE TITLE
Doesn't install anything mentioned on box on windows host

### ISSUE THREAD

**Issue by sagarguhe** [spiritix/vagrant-php7#2]
I tried to install this box on my windows 7 host machine, after running `vagrant up` command it successfully downloaded ubuntu and the setup was complete with error for shared folders, but then when I checked for php7, apache, nodejs installations it was not there on the virtual machine. 

What should be the problem?

**Comment by spiritix** [comment]
Windows as host machine should actually be working fine. Please try to provision the machine again and copy-paste any errors you get.
