### ISSUE TITLE
I have trouble finding where to place the two lines

### ISSUE THREAD

**Issue by allinonebenin** [spiritix/vagrant-php7#4]
Where to place those two lines. I have just done vagrant up. Now, I am wondering where to go and add the lines below 
 192.168.100.100 app.dev
192.168.100.100 phpmyadmin.dev

**Comment by spiritix** [comment]
Hi, you need to add these lines to the 'HOSTS' file on your computer.
Here is how you edit it on Windows: http://www.thewindowsclub.com/hosts-file-in-windows
And here for Mac: http://www.imore.com/how-edit-your-macs-hosts-file-and-why-you-would-want
